[package]
name = "meteorite-core"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
age = "0.12.1"
anyhow = "1.0.102"
keyring-core = "1.0.0"
matrix-sdk = { version = "0.19.0", features = [
    "bundled-sqlite",
    "e2e-encryption",
    "automatic-room-key-forwarding",
    "qrcode",
    "sso-login",
] }
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
sysdirs = { version = "0.9.4", features = ["android-auto"] }
tokio = { workspace = true }
toml = "1.1.2"
webbrowser = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "1.1.0"

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
zbus-secret-service-keyring-store = { version = "1.0.0", features = [
    "crypto-rust",
] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
apple-native-keyring-store = { version = "1.0.0", features = ["protected"] }

[target.'cfg(target_os = "android")'.dependencies]
android-native-keyring-store = "1.0.0"
