[package]
name = "meteorite"
version = "0.1.0"
edition = "2024"
authors = ["Vektrace <contact@vektrace.com>"]
description = "Fast, Secure & Easy-to-use Matrix client in Rust"
license = "AGPL-3.0-only"
repository = "https://github.com/vektrace/meteorite"

[dependencies]
meteorite-core = { path = "../meteorite-core" }

tokio = { workspace = true }
webbrowser = { workspace = true }

dioxus = { version = "0.8.0-alpha.1", features = [] }

[features]
default = ["desktop"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
